const darkmode = true

export const getStyles = (darkmode: boolean) => ({
    popup: {
        position: "fixed",
        zIndex: 999999,
        width: "280px",
        padding: "10px",
        borderRadius: "8px",
        // background: "#efecf9",
        background: darkmode? "linear-gradient(135deg, #473f55, #251848)": "linear-gradient(135deg, #faf7ff, #e7e2f7)",
        border: darkmode? "0.5px solid #070134": "0.5px solid #e2e0f0",
        boxShadow: darkmode? "0 20px 60px rgba(62, 42, 80, 0.62), 0 2px 8px rgba(15,23,42,0.06)": "0 20px 60px rgba(29, 15, 42, 0.14), 0 2px 8px rgba(15,23,42,0.06)",
        fontFamily: "Inter, system-ui, sans-serif",
        overflow: "hidden",
        animation: "popupFadeIn 0.14s ease-out forwards",
        isolation: "isolate",
    } as React.CSSProperties,
    glowBg: {
        position: "absolute",
        inset: 0,
        zIndex: 0,
        pointerEvents: "none",
        borderRadius: "16px",
        overflow: "hidden",
    } as React.CSSProperties,
    glowInner: {
        position: "absolute",
        inset: "-60px",
        background:
            "radial-gradient(circle at 30% 0%, rgba(206,203,246,0.18), transparent 55%)," +
            "radial-gradient(circle at 70% 100%, rgba(196,216,249,0.12), transparent 60%)",
        pointerEvents: "none",
    } as React.CSSProperties,
    glowLine: {
        position: "absolute",
        top: 0,
        left: "12px",
        right: "12px",
        height: "1.5px",
        background: "linear-gradient(90deg, transparent, rgba(168,139,250,0.5), transparent)",
        borderRadius: "2px",
    } as React.CSSProperties,
    inputCard: {
        background: darkmode
            ? "rgba(255, 255, 255, 0.17)"
            : "#ffffff",
        backdropFilter: darkmode ? "blur(16px) saturate(180%)" : "none",
        WebkitBackdropFilter: darkmode ? "blur(16px) saturate(180%)" : "none",
        borderRadius: "8px",
        border: darkmode
            ? "0.5px solid rgba(255, 255, 255, 0.23)"
            : "0.5px solid #e8e6f2",
        boxShadow: darkmode
            ? "inset 0 1px 0 rgba(255, 255, 255, 0.07), 0 8px 32px rgba(0, 0, 0, 0.25)"
            : "none",
        marginBottom: "8px",
        position: "relative",
        zIndex: 2,
    } as React.CSSProperties,
    quoteBlock: {
        maxHeight: "50px",
        overflowY: "auto",
        padding: "2px 8px",
        borderLeft: darkmode? "2px solid #473f55": "2px solid #d4d0f0",
        margin: "10px 10px 0 10px",
    } as React.CSSProperties,
    quoteText: {
        fontSize: "11.5px",
        color: darkmode? "#ececec": "#a09ec0",
        margin: 0,
        lineHeight: "1.6",
        // fontStyle: "italic",
    } as React.CSSProperties,
    divider: {
        height: "0.5px",
        background: darkmode? "rgba(255, 255, 255, 0.23)": "#f0eef8",
        margin: "8px 0 0 0",
    } as React.CSSProperties,
    textarea: {
        width: "100%",
        height: "50px",
        fontSize: "13.5px",
        padding: "12px",
        border: "none",
        background: "transparent",
        color: darkmode? "white": "#1a1830",
        resize: "none",
        outline: "none",
        boxSizing: "border-box",
        fontFamily: "Inter, system-ui, sans-serif",
        lineHeight: "1.6",
    } as React.CSSProperties,
    responseCard: {
        background: darkmode
            ? "rgba(255, 255, 255, 0.17)"
            : "#ffffff",
        backdropFilter: darkmode ? "blur(16px) saturate(180%)" : "none",
        WebkitBackdropFilter: darkmode ? "blur(16px) saturate(180%)" : "none",
        borderRadius: "8px",
        border: darkmode
            ? "0.5px solid rgba(255, 255, 255, 0.23)"
            : "0.5px solid #e8e6f2",
        boxShadow: darkmode
            ? "inset 0 1px 0 rgba(255, 255, 255, 0.07), 0 8px 32px rgba(0, 0, 0, 0.25)"
            : "none",
        marginBottom: "8px",
        marginTop: "18px",
        position: "relative",
        zIndex: 2,
    } as React.CSSProperties,
    responseHeader: {
        padding: "7px 11px",
        borderBottom: darkmode? "0.5px solid rgba(255, 255, 255, 0.23)": "0.5px solid #f0eef8",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
    } as React.CSSProperties,
    responseLabel: {
        display: "flex",
        alignItems: "center",
        gap: "6px",
        fontSize: "10px",
        letterSpacing: "0.06em",
        textTransform: "uppercase",
        color: darkmode? "#d9d4ff": "#a39fc1",
        fontWeight: 500,
    } as React.CSSProperties,
    demoBadge: {
        fontSize: "10px",
        color: "#f6f5ffcb",
        background: "#5546917b",
        padding: "2px 7px",
        borderRadius: "20px",
        border: "0.5px solid #e8e6f2",
    },
    responseBody: {
        padding: "5px 9px",
        fontSize: "13.5px",
        lineHeight: "1.6",
        color: darkmode? "#ffffff": "#1a1830",
    } as React.CSSProperties,
    footer: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        paddingTop: "2px",
        // borderTop: "0.5px solid #e8e6f2",
        position: "relative",
        zIndex: 2,
    } as React.CSSProperties,
    cancelBtn: {
        fontSize: "12px",
        color: "#9692b3",
        background: "transparent",
        border: "none",
        cursor: "pointer",
        padding: 0,
        fontFamily: "Inter, system-ui, sans-serif",
    } as React.CSSProperties,
    footerRight: {
        display: "flex",
        alignItems: "center",
        gap: "7px",
    } as React.CSSProperties,
    sidebarBtn: {
        background: "none",
        border: "0.5px solid #dddbe8",
        borderRadius: "7px",
        padding: "4px 6px",
        cursor: "pointer",
        color: "#b0adc8",
        display: "flex",
        alignItems: "center",
        lineHeight: 1,
    },
    sendBtn: (disabled = false) => ({
        fontSize: "11.5px",
        backgroundColor: disabled ? "#d0ccf4" : "#6c63d5",
        color: "#fff",
        padding: "5px 13px",
        borderRadius: "7px",
        border: "none",
        cursor: disabled ? "not-allowed" : "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: "5px",
        fontFamily: "Inter, system-ui, sans-serif",
        fontWeight: 500,
    }),
    saveBtn: (disabled=false) => ({
        fontSize: "11.5px",
        backgroundColor: disabled ? "#c4c2d8" : "#6c63d5",
        color: "#fff",
        padding: "5px 13px",
        borderRadius: "7px",
        border: "none",
        cursor: disabled ? "not-allowed" : "pointer",
        fontFamily: "Inter, system-ui, sans-serif",
        fontWeight: 500,
        animation: "popupFadeIn 0.18s ease-out forwards",
    }),
    footnote: {
        fontSize: "10px",
        color: "#c4c2d8",
        textAlign: "center",
        margin: "8px 0 0 0",
        position: "relative",
        zIndex: 2,
    } as React.CSSProperties,
    footnoteLink: {
        color: "#c4c2d8",
        textDecoration: "underline",
        cursor: "pointer",
    } as React.CSSProperties,
});